kind: Deployment
apiVersion: apps/v1
metadata:
  name: helloworld-workload
  namespace: kubesphere-docs-dev
  labels:
    app: helloworld-workload
  annotations:
    deployment.kubernetes.io/revision: '4'
    kubesphere.io/alias-name: helloworld-workload
    kubesphere.io/creator: ws-admin
    kubesphere.io/description: helloworld-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-workload
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloworld-workload
    spec:
      containers:
        - name: container-k9nsv6
          image: phutest123/test-helloworld
          ports:
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: TEST_VARIABLE_1
              value: TEST_VALUE_1
            - name: TEST_VARIABLE_2
              value: TEST_VALUE_2
          resources:
            limits:
              cpu: 460m
              memory: 820Mi
            requests:
              cpu: 10m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: helloworld-workload
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
