# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: demo-helloworld
#   # namespace: kubesphere-docs-dev
# spec:
#   selector:
#       matchLabels:
#         app: demo-helloworld
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: demo-helloworld
#     spec:
#       containers:
#         - name: demo-helloworld
#           image: phutest123/devops-docs-sample
#           imagePullPolicy: Never
#           ports:
#             - containerPort: 8080


kind: Service
apiVersion: v1
metadata:
  name: demo-backend
spec:
  selector:
    app: demo-backend
  ports:
  - protocol: TCP
    port: 8080
  type: ClusterIP